// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:inspflutterfrontend/widget/card/model/insp_card_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'my_courses_widget_redux.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
//part 'home_redux.g.dart';

@freezed
class MyCoursesWidgetAppState with _$MyCoursesWidgetAppState {
  const factory MyCoursesWidgetAppState(
          [@Default([]) List<INSPCardModel> myCoursesInspCardModels]) =
      _MyCoursesWidgetAppState;
}
