// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:inspflutterfrontend/widget/card/model/latest_completed_class_card_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'rating_and_feedback_widget_redux.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
//part 'home_redux.g.dart';

@freezed
class RatingFeedbackWidgetAppState with _$RatingFeedbackWidgetAppState {
  const factory RatingFeedbackWidgetAppState({
    required List<LatestCompletedClassCardModel> latestCompletedClassData,
  }) = _RatingFeedbackWidgetAppState;
}
