// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'pdfviewer_redux.freezed.dart';

@freezed
class PDFViewerAppState with _$PDFViewerAppState {
  const factory PDFViewerAppState({@Default('') String fileUrl}) =
      _PDFViewerAppState;
}
