// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:inspflutterfrontend/common/model/insp_card_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'assignment_courses_widget_redux.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
//part 'home_redux.g.dart';

@freezed
class AssignmentCoursesWidgetAppState with _$AssignmentCoursesWidgetAppState {
  const factory AssignmentCoursesWidgetAppState(
          [@Default([]) List<INSPCardModel> assignmentCoursesInspCardModels]) =
      _AssignmentCoursesWidgetAppState;
}
