// // This file is "main.dart"
// import 'package:freezed_annotation/freezed_annotation.dart';
// import 'package:inspflutterfrontend/pages/common/livestream/models/peers_model.dart';

// // required: associates our `main.dart` with the code generated by Freezed
// part 'peers_widget_redux.freezed.dart';

// @freezed
// class PeersWidgetAppState with _$PeersWidgetAppState {
//   const factory PeersWidgetAppState({

//   }) = _PeersWidgetAppState;
// }

// class UpdateAllPeers extends PeersWidgetAction {
//   List<PeersDataModel> allPeers;
//   UpdateAllPeers({required this.allPeers});
// }

// sealed class PeersWidgetAction {}

// PeersWidgetAppState _peersMessageStateReducer(
//     PeersWidgetAppState state, PeersWidgetAction action) {
//   switch (action) {
//     case UpdateAllPeers():
//       return state.copyWith(allPeers: action.allPeers);
//   }
// }

// PeersWidgetAppState peersMessageStateReducer(
//     PeersWidgetAppState state, dynamic action) {
//   var upState = _peersMessageStateReducer(state, action);
//   return upState;
// }
