// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

import '../data/remote/models/mycourses/all_lectures_for_course_response_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'upcoming_class_widget_redux.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
//part 'home_redux.g.dart';

@freezed
class UpcomingWidgetAppState with _$UpcomingWidgetAppState {
  const factory UpcomingWidgetAppState({
    required List<AllLecturesForCourseResponseModelData> ongoing,
    required List<AllLecturesForCourseResponseModelData> today,
    required List<AllLecturesForCourseResponseModelData> week,
    required List<AllLecturesForCourseResponseModelData> completed,
  }) = _UpcomingWidgetAppState;
}
