// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:inspflutterfrontend/common/model/upcoming_lecture_card_model.dart';
import 'package:inspflutterfrontend/data/remote/models/mycourses/all_lectures_for_course_response_model.dart';
import 'package:inspflutterfrontend/data/remote/remote_data_source.dart';
import 'package:redux/redux.dart';
import 'package:redux_thunk/redux_thunk.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'upcoming_class_widget_redux.freezed.dart';

@freezed
class UpcomingWidgetAppState with _$UpcomingWidgetAppState {
  const factory UpcomingWidgetAppState({
    @Default([]) List<AllLecturesForCourseResponseModelData> ongoing,
    @Default([]) List<AllLecturesForCourseResponseModelData> today,
    @Default([]) List<AllLecturesForCourseResponseModelData> week,
    @Default([]) List<AllLecturesForCourseResponseModelData> completed,
    @Default(UpcomingLectureCardModel([], [], [], []))
    UpcomingLectureCardModel weeklyData,
  }) = _UpcomingWidgetAppState;
}

// Reducer
UpcomingWidgetAppState upcomingWidgetReducer(
    UpcomingWidgetAppState state, dynamic action) {
  return _upcomingWidgetReducer(state, action);
}

// Action
abstract class UpcomingWidgetAction {}

class UpdateWeeklyData extends UpcomingWidgetAction {
  final UpcomingLectureCardModel weeklyData;

  UpdateWeeklyData({required this.weeklyData});
}

UpcomingWidgetAppState _upcomingWidgetReducer(
    UpcomingWidgetAppState state, UpcomingWidgetAction action) {
  if (action is UpdateWeeklyData) {
    return state.copyWith(weeklyData: action.weeklyData);
  }
  return state;
}

// Thunk action
ThunkAction<UpcomingWidgetAppState> getAllUpcomingClass(BuildContext context) {
  return (Store<UpcomingWidgetAppState> store) async {
    try {
      final remoteDataSource = RemoteDataSource();
      const token = 'Token ccee6a1685a4687a385be0f6e733ff23';
      final allLecture = await remoteDataSource.getAllUpcomingClasses(token);
      final UpcomingLectureCardModel allSubjectsResults =
          UpcomingLectureCardModel(
              allLecture.data.data.ongoing,
              allLecture.data.data.today,
              allLecture.data.data.week,
              allLecture.data.data.completed);

      print(allSubjectsResults);

      store.dispatch(UpdateWeeklyData(weeklyData: allSubjectsResults));
    } catch (error) {
      // Handle errors appropriately here
      print('Error fetching data: $error');
    }
  };
}
