// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:insp/apiservices/models/login/login_response_model.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'userdata_redux.freezed.dart';

@freezed
class UserDataAppState with _$UserDataAppState {
  const factory UserDataAppState(
      [@Default(LoginResponseModelResult())
      LoginResponseModelResult userData]) = _UserDataAppState;
}

sealed class UserAction {}

class UpdateUserData extends UserAction {
  LoginResponseModelResult userData;

  UpdateUserData({required this.userData});
}

UserDataAppState userStateReducer(UserDataAppState state, dynamic action) {
  if (action is UpdateUserData) {
    return state.copyWith(userData: action.userData);
  }
  return state;
}
