// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:inspflutterfrontend/widget/card/model/latest_assignment_card_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'myupload_widget_redux.freezed.dart';

@freezed
class MyUploadWidgetAppState with _$MyUploadWidgetAppState {
  const factory MyUploadWidgetAppState({
    required List<LatestAssignmentCardModel> myUploadData,
  }) = _MyUploadWidgetAppState;
}
