// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:insp/apiservices/models/feedback/create_student_feedback_request_model.dart';
import 'package:insp/apiservices/models/login/login_response_model.dart';
import 'package:insp/apiservices/remote_data_source.dart';
import 'package:insp/utils/toaster.dart';
import 'package:insp/utils/userDetail/getUserDetail.dart';
import 'package:redux/redux.dart';
import 'package:redux_thunk/redux_thunk.dart';
import 'package:toastification/toastification.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'student_suggestion_redux.freezed.dart';

@freezed
class StudentSuggestionAppState with _$StudentSuggestionAppState {
  const factory StudentSuggestionAppState(
      {@Default('') String? feedback,
      @Default('') String? feedbackError}) = _StudentSuggestionAppState;
}

sealed class StudentSuggestionAction {}

class UpdateFeedback extends StudentSuggestionAction {
  String? feedback;
  UpdateFeedback({required this.feedback});
}

StudentSuggestionAppState _studentSuggestionStateReducer(
    StudentSuggestionAppState state, StudentSuggestionAction action) {
  switch (action) {
    case UpdateFeedback():
      return state.copyWith(feedback: action.feedback, feedbackError: '');
  }
}

StudentSuggestionAppState studentSuggestionStateReducer(
    StudentSuggestionAppState state, dynamic action) {
  var upState = _studentSuggestionStateReducer(state, action);
  return upState;
}

ThunkAction<StudentSuggestionAppState> studentSuggestionapi(
    BuildContext context) {
  return (Store<StudentSuggestionAppState> store) async {
    try {
      if (store.state.feedback != '') {
        LoginResponseModelResult userData = getUserDataFromStore(context);
        CreateStudentFeedbackRequestModel suggestionRequest =
            CreateStudentFeedbackRequestModel(
                feedback: store.state.feedback ?? '',
                studentEmail: userData.email,
                studentName: userData.name);
        final remoteDataSource = RemoteDataSource();
        final deleteTopicData = await remoteDataSource.createStudentFeedback(
            suggestionRequest, 'Token ${userData.token}');

        if (deleteTopicData.response.statusCode == 200) {
          Navigator.of(context).pop();
          showToast(context, 'Suggestion submitted Succesfully',
              ToastificationType.success);
        } else {
          Navigator.of(context).pop();
          showToast(context, 'Some issue, please try again',
              ToastificationType.warning);
        }
      } else {
        showToast(
            context, 'Please insert suggestion', ToastificationType.warning);
      }
    } catch (error) {
      Navigator.of(context).pop();
      showToast(
          context, 'Some issue, please try again', ToastificationType.error);
    }
  };
}
